---
# The following ansible playbook will add a user, then add an
# authorized_key for that user, using two built in modules.
- name: Add user and key
  hosts: localhost
  become: true

  tasks:

    - name: Add User
      ansible.builtin.user:
        name: unprivileged

    - name: Add Key
      authorized_key:
        user: unprivileged
        key: "{{ lookup('file', '/home/ec2-user/unprivileged-key.pub') }}"
        state: present
